name: Publish release

on:
  push:
    tags:
      - "v*.*.*"
    
  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Install dependencies
        run: npm ci
      - name: Install tools
        run: |
          npm install @craco/craco --save
          npm install generate-license-file -g
      - name: Build optimized web app
        run: npm run build --if-present
      - name: Prepare package
        run: mkdir -p package
      - name: Generate third party licenses
        run: generate-license-file --input package.json --output package/third-party-licenses.txt --overwrite
      - name: Package
        run: |
          chmod +x scripts/*
          cp scripts/* package/
          cp -r build package/
          cp LICENSE package/
          cd package
          tar zcf ../laserweb-kiosk-${{ steps.get_version.outputs.VERSION }}.tgz --owner=0 --group=0 .
          tar tzvf ../laserweb-kiosk-${{ steps.get_version.outputs.VERSION }}.tgz
      - name: Upload the package
        uses: actions/upload-artifact@v2
        with:
          name: Release package
          path: laserweb-kiosk-${{ steps.get_version.outputs.VERSION }}.tgz
      - name: Release
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            LICENSE
            laserweb-kiosk-${{ steps.get_version.outputs.VERSION }}.tgz

